spring.application.name=api-gateway
server.port=8080
# =========================
# Redis
# =========================

spring.data.redis.host=redis
spring.data.redis.port=6379


# =========================
# Account Service
# =========================

spring.cloud.gateway.routes[0].id=account-service
spring.cloud.gateway.routes[0].uri=http://account-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/accounts/**

spring.cloud.gateway.routes[0].filters[0]=RequestRateLimiter
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.replenishRate=10
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.burstCapacity=10
spring.cloud.gateway.routes[0].filters[0].args.key-resolver=#{@keyResolver}


# =========================
# Transaction Service
# =========================

spring.cloud.gateway.routes[1].id=transaction-service
spring.cloud.gateway.routes[1].uri=http://transaction-service:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/transactions/**

spring.cloud.gateway.routes[1].filters[0]=RequestRateLimiter
spring.cloud.gateway.routes[1].filters[0].args.redis-rate-limiter.replenishRate=10
spring.cloud.gateway.routes[1].filters[0].args.redis-rate-limiter.burstCapacity=10
spring.cloud.gateway.routes[1].filters[0].args.key-resolver=#{@keyResolver}


# =========================
# Payment Service
# =========================

spring.cloud.gateway.routes[2].id=payment-service
spring.cloud.gateway.routes[2].uri=http://payment-service:8084
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/payments/**

spring.cloud.gateway.routes[2].filters[0]=RequestRateLimiter
spring.cloud.gateway.routes[2].filters[0].args.redis-rate-limiter.replenishRate=10
spring.cloud.gateway.routes[2].filters[0].args.redis-rate-limiter.burstCapacity=10
spring.cloud.gateway.routes[2].filters[0].args.key-resolver=#{@keyResolver}


# =========================
# Fraud Detection Service
# =========================

spring.cloud.gateway.routes[3].id=fraud-detection-service
spring.cloud.gateway.routes[3].uri=http://fraud-detection-service:8083
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/fraud/**

spring.cloud.gateway.routes[3].filters[0]=RequestRateLimiter
spring.cloud.gateway.routes[3].filters[0].args.redis-rate-limiter.replenishRate=10
spring.cloud.gateway.routes[3].filters[0].args.redis-rate-limiter.burstCapacity=10
spring.cloud.gateway.routes[3].filters[0].args.key-resolver=#{@keyResolver}


management.endpoints.web.exposure.include=health,info
