spring.application.name=api-gateway
server.port=8080
spring.main.web-application-type=reactive

# =========================
# Redis
# =========================

spring.data.redis.host=localhost
spring.data.redis.port=6379

# =========================
# Actuator
# =========================

management.endpoints.web.exposure.include=health,info,gateway

# =========================
# Swagger
# =========================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.urls[0].name=Account Service
springdoc.swagger-ui.urls[0].url=/docs/account-service/v3/api-docs
springdoc.swagger-ui.urls[1].name=Transaction Service
springdoc.swagger-ui.urls[1].url=/docs/transaction-service/v3/api-docs
springdoc.swagger-ui.urls[2].name=Fraud Detection Service
springdoc.swagger-ui.urls[2].url=/docs/fraud-detection-service/v3/api-docs
springdoc.swagger-ui.urls[3].name=Payment Service
springdoc.swagger-ui.urls[3].url=/docs/payment-service/v3/api-docs
springdoc.swagger-ui.urls[4].name=Notification Service
springdoc.swagger-ui.urls[4].url=/docs/notification-service/v3/api-docs
