spring.application.name=payment-service
server.port=8084

spring.datasource.url=jdbc:mariadb://localhost:3307/payment_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=your_password

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=60000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Kafka
spring.kafka.bootstrap-servers=localhost:9092


# ==================== Producer ====================
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
management.endpoints.web.exposure.include=health,info

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ===================== Paymob Configuration =====================
paymob.secret-key=${PAYMOB_SECRET_KEY:}
paymob.integration-id=${PAYMOB_INTEGRATION_ID:}
paymob.base-url=https://accept.paymob.com
paymob.public-key=${PAYMOB_PUBLIC_KEY:}
paymob.hmac-secret=${PAYMOB_HMAC_KEY:}

