spring.application.name=payment-service
server.port=8084

spring.datasource.url=jdbc:mariadb://localhost:3307/payment_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=your_password

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=60000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Kafka
spring.kafka.bootstrap-servers=localhost:9092


# ==================== Producer ====================
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
management.endpoints.web.exposure.include=health,info

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ===================== Paymob Configuration =====================
paymob.secret-key=egy_sk_test_dd4009d7ff8222afaeb1dab0093d6bbf63b754bc9375db85ac18f349ee7b5dbf
paymob.integration-id=5553517
paymob.base-url=https://accept.paymob.com
paymob.public-key=egy_pk_test_9aZBjzViJKQliY9xnlo95kn9gUM8lOJl
paymob.hmac-secret=6BAEB0CFDB4EDA501C4DC21B32B0F15C