spring.application.name=fraud-detection-service
server.port=8083
spring.kafka.consumer.group-id=fraud-detection-group
fraud.max-transaction-per-minute=5

fraud.suspicious-amount-miultiplier=5
fraud.max-balance-percentage=0.90
