spring.application.name=fraud-detection-service
server.port=8083
spring.kafka.consumer.group-id=fraud-detection-group
fraud.max-transaction-per-minute=5

fraud.suspicious-amount-miultiplier=5
fraud.max-balance-percentage=0.90
# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# ==================== Consumer ====================
spring.kafka.consumer.group-id=transaction-service-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=java.util.HashMap

# ==================== Producer ====================
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
management.endpoints.web.exposure.include=health,info
